sudo: required
dist: xenial
addons:
  chrome: stable
language: java
jdk: openjdk8
services: 
- mysql
- xvfb
before deploy:
    -pip install travis-wait-improved
install: true
before_script:
    - sudo apt-get install libnss3
    - export DISPLAY=:99.0
    - sleep 3
script:
    - mvn install
    - whereis google-chrome-stable
before_install:
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y
  - sudo mysql -e 'CREATE DATABASE alumnos; USE alumnos; CREATE TABLE alumnos.Alumno (idAlumno int(11) NOT NULL, nombre varchar(45) DEFAULT NULL, edad int(11) DEFAULT NULL, calificacion int(11) DEFAULT NULL, email varchar(45) DEFAULT NULL, PRIMARY KEY (idAlumno));'
  - sudo chmod +x /home/travis/build/leonelsosav/my-app/src/test/resources/chromedriver
  - google-chrome-stable --headless --disable gpu --remotre-debugging-port=9222 http://localhost &